# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Gtk2-Ex-TreeMaker
version:      0.10
version_from: lib/Gtk2/Ex/TreeMaker.pm
installdirs:  site
requires:
    Carp:                          0
    Data::Dumper:                  0
    Glib:                          0
    Gtk2:                          0
    Gtk2::TestHelper:              0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
